### ISSUE TITLE
Email scope for google access not set

### ISSUE THREAD

**Issue by bettiolo** [dashy-io/dashy-admin-ui#21]
We are not recoding any more users' email addresses. The scope when doing Google authentication needs to be fixed.

**Comment by bettiolo** [comment]
The correct scope is:
`https://www.googleapis.com/auth/plus.profile.emails.read`
instead the app is currently using:
`profile`

**Comment by bettiolo** [comment]
This is critical, we cannot go 1.0.0 without it.

**Comment by mtt87** [comment]
Changed, can you check if it's working fine? @bettiolo
